### ISSUE TITLE
Consider Read the Docs as an alternative to manual deploy process

### ISSUE THREAD

**Issue by supertylerc** [supertylerc/jncip-dc-notes#3]
Suggestion came in from @mirceaulinic via Twitter to use Read the Docs instead of manually publishing.  Largest advantage seems to be automatic PDF generation.  Sphinx can definitely do this, but it would be a manual process (though since I already use a `make` target, it could just be a part of that, too...but it would be nice to not have tons of PDF revisions in source control).

Steps:

- [x] Sign up at http://readthedocs.io
- [x] Give access to my GitHub profile and select this repository
- [x] Test PDF generation
- [ ] If everything looks good, update the `CNAME` for `jncip-dc.tylerc.me` to point to the new domain (probably `jncip-dc-notes.readthedocs.io`), otherwise close this issue and maintain the status quo

**Comment by supertylerc** [comment]
I really like RtD.  It simplifies the build process and allows for automatic PDF generation with each commit without polluting the repo.

But it has ads.  :/  I understand and appreciate the need for them to have ads, but I don't personally want the ads to be associated with this project.  My goal is an ad-free, affiliate-free experience, where no one feels like I'm trying to make money off of their visits.

It looks like I can get ads removed by paying a certain amount of money, which I'm open to, but I'd like to understand their model a bit better.  If I can do a one-time contribution and be ad-free for life, then I would be open to that.  However, if I need to pay a monthly fee to remain ad-free, I would just as soon stick to the current method of publishing to GitHub pages, which has no ads.

**Comment by supertylerc** [comment]
Another issue with RtD is that the PDF generation seems to think Chapter 1 is `Contributing`.  It should be `Data Center Deployment and Management`.  I'm not sure why this is happening, but it's definitely something I'd want to fix.

**Comment by mirceaulinic** [comment]
Hey @supertylerc :wave: I've went ahead and submitted #17 if you'd like to consider this as an alternative. I know that readthedocs has ads and it's a bit annoying, and understand your reasoning behind not wanting to use them because of this. Hope my PR helps!

Re:

> Another issue with RtD is that the PDF generation seems to think Chapter 1 is Contributing. It should be Data Center Deployment and Management

This is due to the ToC tree in the index, we can work out around that, but firstly want to hear your thoughts on the PR as-is and if you like this approach, I'll continue working on it in this direction. Cheers!

**Comment by supertylerc** [comment]
I've merged #17.  Thank you!  I'm going to close this issue as it seems RtD is a non-starter for now.
